lucide.createIcons();
// Firebase config
const firebaseConfig = { apiKey: "AIzaSyCh7Ute6LeSAxcNDEQwZg5m0cA4ujnLCfg", authDomain: "test-17881.firebaseapp.com", projectId: "test-17881", storageBucket: "test-17881.firebasestorage.app", messagingSenderId: "1057428047643", appId: "1:1057428047643:web:f3801c0d933225a5cd35be" };
firebase.initializeApp(firebaseConfig);
const db = firebase.database();
const auth = firebase.auth();
const MAPBOX_TOKEN = 'pk.eyJ1Ijoia2F0bGVnb3BoYXNoYSIsImEiOiJjbTlpOTdzbmYwMGNsMmpzYWJtZzN4d3pqIn0.Zt-aSMEoahrV3zkiVVHbOw';
const CLOUDINARY_CLOUD = 'dqkujefxj';
const CLOUDINARY_PRESET = 'banter_box';
async function uploadToCloudinary(file, onProgress) { const fd = new FormData(); fd.append('file', file); fd.append('upload_preset', CLOUDINARY_PRESET); fd.append('folder', 'vynix_menu'); return new Promise((resolve, reject) => { const xhr = new XMLHttpRequest(); xhr.open('POST', `https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD}/image/upload`); xhr.upload.addEventListener('progress', e => { if (e.lengthComputable && onProgress) onProgress(Math.round((e.loaded/e.total)*100)); }); xhr.onload = () => { if (xhr.status === 200) resolve(JSON.parse(xhr.responseText).secure_url); else reject(new Error('Upload failed: ' + xhr.statusText)); }; xhr.onerror = () => reject(new Error('Network error during upload')); xhr.send(fd); }); }
function previewItemImage(input) { const file = input.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = e => { document.getElementById('item-img-preview').src = e.target.result; document.getElementById('item-img-preview-wrap').style.display = 'block'; }; reader.readAsDataURL(file); }
// Store configs (truncated for brevity, but keep essential)
const STORE_CONFIGS = { restaurant: { storeType:'restaurant', label:'Restaurant', emoji:'🍽️', logoSuffix:'EATS', logoIcon:'utensils', theme:'restaurant', heroTitle: n => `Welcome back, ${n}! ☀️`, heroSub:'Manage your restaurant.', welcomeTitle:'Restaurant Portal', welcomeDesc:'Manage your menu, track orders.', welcomeTips:['🍕 Feature bestsellers','⏱️ Update prep times','📸 Upload quality photos'], navMenuLabel:'Menu Items', navMenuIcon:'book-open', navOrdersLabel:'Orders', navOrdersIcon:'shopping-bag', navProfileLabel:'Store Profile', navProfileIcon:'store', menuPageTitle:'Menu Items', ordersPageTitle:'Orders', profilePageTitle:'Restaurant Profile', featuredPageTitle:'Featured Dishes', addItemBtnLabel:'Add Dish', itemNameLabel:'Dish Name *', itemPriceLabel:'Price (R) *', itemPrepLabel:'Prep Time (mins)', itemCalLabel:'Calories', itemTagLabel:'Allergens', profileSectionTitle:'Restaurant Identity', cuisineLabel:'Cuisine Type', minOrderLabel:'Min. Order Value (R)', preptimeLabel:'Avg. Prep Time (mins)', setOpenLabel:'Restaurant is Open', setDeliveryLabel:'Delivery Available', setDeliverySub:'Offer delivery', setPickupLabel:'Takeaway Available', setPickupSub:'Allow collection', setOrderAlertLabel:'New Order Alerts', setOrderAlertSub:'Sound & visual alert', anaItemsLabel:'Menu Items', anaOrdersLabel:'Total Orders', catBreakdownTitle:'Menu by Category', emptyOrdersEmoji:'🍽️', emptyOrdersText:'No orders yet', stats:[{id:'stat-menu',label:'Menu Items',icon:'package'},{id:'stat-featured',label:'Featured Dishes',icon:'star'},{id:'stat-orders',label:'Total Orders',icon:'shopping-bag'},{id:'stat-pending',label:'Pending Orders',icon:'clock'},{id:'stat-revenue',label:'Est. Revenue',icon:'trending-up',prefix:'R '}], quickActions:[{icon:'plus',label:'Add Dish',fn:'openAddItemModal()'},{icon:'star',label:'Featured',fn:"showTab('featured',document.querySelectorAll('.nav-item')[2])"},{icon:'edit-2',label:'Edit Profile',fn:"showTab('profile',document.querySelectorAll('.nav-item')[5])"},{icon:'bar-chart-3',label:'Analytics',fn:"showTab('analytics',document.querySelectorAll('.nav-item')[4])"}], menuCategories:['Starters','Mains','Burgers','Pizza','Salads','Desserts','Drinks','Sides','Specials','Breakfast','Seafood'], shopCategories:[{v:'Pizza',e:'🍕'},{v:'Burgers',e:'🍔'},{v:'Sushi',e:'🍣'},{v:'Healthy',e:'🥗'},{v:'Desserts',e:'🍰'},{v:'Fast Food',e:'🍟'},{v:'African',e:'🇿🇦'},{v:'Indian',e:'🍛'},{v:'Chinese',e:'🥟'},{v:'Italian',e:'🍝'},{v:'Chicken',e:'🍗'},{v:'Seafood',e:'🦐'},{v:'Vegetarian',e:'🌱'},{v:'Drinks',e:'🥤'},{v:'Coffee',e:'☕'},{v:'Bakery',e:'🧁'},{v:'Halaal',e:'☪️'},{v:'Breakfast',e:'🍳'}], recentOrdersTitle:'🕐 Recent Orders', featuredBannerTitle:'Featured dishes appear on the customer app homepage' } };
STORE_CONFIGS.grocery = { ...STORE_CONFIGS.restaurant, storeType:'grocery', label:'Grocery Store', emoji:'🛒', logoSuffix:'SHOP', logoIcon:'shopping-basket', theme:'grocery' };
STORE_CONFIGS.alcohol = { ...STORE_CONFIGS.restaurant, storeType:'alcohol', label:'Bottle Store', emoji:'🍷', logoSuffix:'POUR', logoIcon:'wine', theme:'alcohol' };
STORE_CONFIGS.health = { ...STORE_CONFIGS.restaurant, storeType:'health', label:'Health & Pharmacy', emoji:'💊', logoSuffix:'CARE', logoIcon:'heart-pulse', theme:'health' };
STORE_CONFIGS.pets = { ...STORE_CONFIGS.restaurant, storeType:'pets', label:'Pet Store', emoji:'🐾', logoSuffix:'PAWS', logoIcon:'dog', theme:'pets' };
STORE_CONFIGS.electronics = { ...STORE_CONFIGS.restaurant, storeType:'electronics', label:'Electronics Store', emoji:'📱', logoSuffix:'TECH', logoIcon:'smartphone', theme:'electronics' };
